spring:
  datasource:
    url: jdbc:mysql://mysqlaws.cbmlkigba5xb.us-east-2.rds.amazonaws.com:3306/testdb
    username: jayala
    password: vincaqui01
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL5Dialect
    
    